"""Ports — the interfaces the engine/API depend on (SYSTEM_DESIGN §4).

These are structural `Protocol`s: adapters conform by shape, without importing or
subclassing anything here. Concrete conformance is checked by mypy wherever an adapter
is assigned to a port type (see api/deps.py) and at runtime via @runtime_checkable.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

from quant_pilot.domain.models import (
    ArtifactRef,
    AuditEvent,
    BacktestRun,
    Instrument,
    JobStatus,
    MarginInfo,
    Order,
    Position,
    StrategyConfig,
    UniverseMembership,
)

if TYPE_CHECKING:  # pandas is an engine-phase dependency, not a platform one.
    import pandas as pd


@runtime_checkable
class Clock(Protocol):
    """Injected time source so backtests are deterministic and look-ahead-free."""

    def now(self) -> datetime: ...
    def today(self) -> date: ...


@runtime_checkable
class SecretStore(Protocol):
    """Broker credentials etc. Never stored in repo/DB plaintext (SYSTEM_DESIGN §8.3)."""

    def get_secret(self, name: str) -> str | None: ...
    def set_secret(self, name: str, value: str) -> None: ...
    def delete_secret(self, name: str) -> None: ...


@runtime_checkable
class ArtifactStore(Protocol):
    """Tearsheets, plots, large result blobs — addressed by key, returned as ArtifactRef."""

    def save_bytes(
        self, key: str, data: bytes, content_type: str = "application/octet-stream"
    ) -> ArtifactRef: ...
    def save_json(self, key: str, obj: Any) -> ArtifactRef: ...
    def load_bytes(self, key: str) -> bytes: ...
    def load_json(self, key: str) -> Any: ...
    def exists(self, key: str) -> bool: ...
    def uri_for(self, key: str) -> str: ...


@runtime_checkable
class Repository(Protocol):
    """Transactional persistence of small, queryable state."""

    # strategy configs
    def save_strategy_config(self, cfg: StrategyConfig) -> StrategyConfig: ...
    def get_strategy_config(self, config_id: str) -> StrategyConfig | None: ...

    # backtest runs
    def create_backtest_run(self, run: BacktestRun) -> BacktestRun: ...
    def update_backtest_run(self, run: BacktestRun) -> BacktestRun: ...
    def get_backtest_run(self, run_id: str) -> BacktestRun | None: ...
    def list_backtest_runs(self, *, limit: int = 50, offset: int = 0) -> list[BacktestRun]: ...

    # audit (append-only)
    def append_audit(self, event: AuditEvent) -> AuditEvent: ...
    def list_audit(self, *, limit: int = 100) -> list[AuditEvent]: ...

    # orders (live book history)
    def save_order(self, order: Order) -> Order: ...
    def get_order(self, order_id: str) -> Order | None: ...
    def list_orders(self, *, limit: int = 100) -> list[Order]: ...

    # instruments + point-in-time universe
    def upsert_instrument(self, instrument: Instrument) -> Instrument: ...
    def get_instrument(self, symbol: str) -> Instrument | None: ...
    def add_universe_membership(self, rows: list[UniverseMembership]) -> int: ...
    def get_universe_membership(self, index: str, as_of: date) -> list[UniverseMembership]: ...


@runtime_checkable
class JobQueue(Protocol):
    """Enqueue long work (backtests, ingestion) and query its status."""

    def enqueue(self, func: str, *args: Any, **kwargs: Any) -> str: ...
    def status(self, job_id: str) -> JobStatus: ...


@runtime_checkable
class MarketDataProvider(Protocol):
    """OHLCV, point-in-time universe, liquidity, option chains (engine-phase adapters)."""

    def get_ohlcv(
        self, symbol: str, start: date, end: date, frequency: str = "1d"
    ) -> pd.DataFrame: ...
    def get_universe_membership(self, index: str, as_of: date) -> list[UniverseMembership]: ...
    def get_liquidity(self, symbol: str, as_of: date) -> dict[str, float]: ...
    def get_option_chain(self, underlying: str, expiry: date | None = None) -> pd.DataFrame: ...


@runtime_checkable
class Broker(Protocol):
    """Execution boundary. PaperBroker now; Kite/SmartAPI later (SYSTEM_DESIGN §4)."""

    def get_positions(self) -> list[Position]: ...
    def get_margin(self) -> MarginInfo: ...
    def place_order(self, order: Order) -> Order: ...
    def modify_order(self, order_id: str, **changes: Any) -> Order: ...
    def cancel_order(self, order_id: str) -> Order: ...
    def get_orders(self) -> list[Order]: ...
